# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/JS-DevTools/eslint-config-modular

root: true

extends:
  - modular/best-practices
  - modular/style
  - modular/node
  - modular/es6

rules:
  # The APIs that we're using require snake_case
  camelcase: off

  # Loosen some rules to make the code easier for different skill levels
  strict: off
  object-curly-spacing: off
  quotes:
    - error
    - double

